# You can customize the blocks that can appear in the tiers here. 
# Format: id.meta
# The blocks list can be viewed at: https://www.digminecraft.com/lists/item_id_list_pe.php
# Config Customized/Edited By (EXTER LEO)

1: #Plains
- "3.1"
- "14.0"
- "15.0"
- "16.0"
- "21.0"
- "56.0"
- "73.0"
- "129.0"
- "3.0"
- "110.0"
- "18.0"
- "18.1"
- "18.2"
- "18.3"
- "161.0"
- "161.1"
- "17.0"
- "17.1"
- "17.2"
- "17.3"
- "162.0"
- "162.1"
- "4.0"
- "1.0"
- "1.1"
- "1.3"
- "1.5"
- "13.0"
- "208.0"
- "82.0"
- "12.0"
- "100.1"
- "99.0"
- "99.1"
2: #Underground
- "14.0"
- "15.0"
- "16.0"
- "21.0"
- "56.0"
- "73.0"
- "129.0"
- "1.0"
- "1.1"
- "1.5"
- "1.3"
- "13.0"
- "3.0"
- "3.1"
- "49.0"
- "24.0"
- "5.0"
- "30.0"
3: #Winter
- "4.0"
- "1.0"
- "12.0"
- "3.0" # Help rate out more
- "18.1"
- "17.1"
- "79.0"
- "174.0"
- "14.0"
- "21.0"
- "80.1"
4: #Ocean
- "3.0"
- "1.5"
- "24.0"
- "179.0" # Help rate out more
- "19.1"
- "13.0"
- "168.0"
- "168.1"
- "168.2"
- "12.0"
- "1.1"
- "82.0"
- "19.0"
- "169.0"
5: #Jungle
- "16.0"
- "56.0" # Help rate out more
- "21.0"
- "73.0"
- "15.0"
- "14.0"
- "1.0"
- "129.0"
- "3.0"
- "110.0"
- "13.0"
- "2.0"
- "86.0"
- "4.0"
- "3.1"
- "18.3"
- "17.3"
- "103.0"
- "3.0"
6: #Swamp
- "15.0"
- "16.0"
- "14.0"
- "56.0" # Help rate out more
- "129.0"
- "21.0"
- "73.0"
- "13.0"
- "2.0"
- "4.0"
- "3.1"
- "3.0"
- "17.0"
- "18.0"
- "1.0"
- "82.0"
7: #Dungeon
- "13.0"
- "16.0"
- "73.0"
- "56.0" # Help rate out more
- "14.0"
- "15.0"
- "129.0"
- "21.0"
- "97.1"
- "4.0"
- "12.0"
- "5.0"
- "1.1"
- "1.0"
- "2.0"
- "97.0"
- "1.5"
- "24.0"
- "100.1"
- "1.3"
- "48.0"
8: #Desert
- "12.0"
- "24.0"
- "24.3"
- "12.1" # Help rate out more
- "179.0"
- "1.0"
9: #Nether
- "13.0"
- "153.0"
- "87.0"
- "88.0"
- "215.0"
- "112.0" # Help rate out more
- "89.0"
- "213.0"
10: #The End
- "201.0"
- "121.0"
- "206.0"
- "49.0" # Help rate out more
- "172.0"
- "201.2"

# Chest Items
items: #id.meta.count
- "364.0.5"
- "278.0.1"
- "50.0.1"